name: CD-Staging

on:
  push:
    branches: [ main ]   # deploy staging on pushes to main

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login to ACR
      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build & push BACKEND image
      - name: Build backend image
        run: |
          docker build \
            -f docker/Dockerfile.backend \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/clipcloud-backend:${{ github.sha }} \
            .
      - name: Push backend image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/clipcloud-backend:${{ github.sha }}

      # Build & push FRONTEND image
      - name: Build frontend image
        run: |
          docker build \
            -f docker/Dockerfile.frontend \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/clipcloud-frontend:${{ github.sha }} \
            .
      - name: Push frontend image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/clipcloud-frontend:${{ github.sha }}

      # Deploy backend container to STAGING API app
      - name: Deploy backend to staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: "com769-b01012460-staging"       # <-- your backend staging app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API_STAGING }}
          images: "${{ secrets.ACR_LOGIN_SERVER }}/clipcloud-backend:${{ github.sha }}"

      # Deploy frontend container to STAGING WEB app
      - name: Deploy frontend to staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: "com769-b01012460-web-staging"       # <-- your frontend staging app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB_STAGING }}
          images: "${{ secrets.ACR_LOGIN_SERVER }}/clipcloud-frontend:${{ github.sha }}"
